repos:
  # remove unused imports
  # additional configs are in the pyproject.toml file
  - repo: https://github.com/hadialqattan/pycln.git
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]

  # import formatter with black configurations
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]

  # Code formatter for both python files and jupyter notebooks
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
      - id: black
        language_version: python3.10

  # adding ruff with auto fix on
  # additional configs are in the pyproject.toml file
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.265"
    hooks:
      - id: ruff
        args: [--config=pyproject.toml, --fix, --exit-non-zero-on-fix]

  # additional pre-commits that supports python formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"