---
title: 'SMARTDADA2: Interactive Output'
output: html_document
params: 
  trim_file: "file_path"
  sumEE_file: "file_path"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(include = FALSE)
knitr::opts_chunk$set(warning = FALSE)

# Check dependecies 
packages <- c("readr", "dplyr", "reshape2", "ggplot2", "argparse", "plotly", "cowplot", "rmarkdown")

for (package in packages) {
  if(!require(package, character.only = T)){
    install.packages(package)
    library(package)
  }
}
```

```{r}
sumEE_info <- read_delim(paste0("../../" ,sumEE_file), 
                         delim = "\t", escape_double = FALSE, 
                         trim_ws = TRUE)
trim_info <- read_delim(paste0("../../" ,trim_file), 
                        delim = "\t", escape_double = FALSE, 
                        col_types = cols(LeftIndex = col_integer(),
                                         RightIndex = col_integer(), 
                                         ReadLength = col_integer()),
                        trim_ws = TRUE)
```

```{r}
HeatMap <- ggplot(trim_info, aes(LeftIndex, RightIndex, fill= AvgEEPerPosition)) +
            geom_tile() +
            scale_y_continuous(trans = "reverse", breaks = unique(trim_info$RightIndex)) +
            scale_fill_gradient(low="white", high="blue") +
            theme_bw() + 
            theme(plot.title = element_text(hjust = 0.5), 
                  text = element_text(size = 14), 
                  axis.text.x = element_text(size = 10),
                  axis.text.y = element_text(size = 10)) +
            ggtitle("With Obvious Trimming")

ScatterPlot <- ggplot(trim_info, aes(ReadLength, AvgEEPerPosition)) +
                geom_point() +
                theme_bw() +
                theme(text = element_text(size = 14)) +
                ylab('Average Expected Error Per Position') +
                xlab('Read Length (bp)')

melt_sumEEInfo <- melt(sumEE_info)
Histogram <- ggplot(melt_sumEEInfo, aes(x = value, fill = variable)) +
              geom_histogram(position = "dodge") +
              theme_bw() +
              theme(text = element_text(size = 14)) +
              scale_x_continuous(limits = c(0,4)) +
              guides(fill=guide_legend(title=" "))+
              xlab('Sum of Expected Error')

pHeatMap <- ggplotly(HeatMap)
pScatterPlot <- ggplotly(ScatterPlot)
pHistogram <- ggplotly(Histogram)
```

```{r html widget, include=TRUE}
#subplot(pHeatMap, pScatterPlot)
pHeatMap
pScatterPlot
pHistogram
```


